name: Generate Datas

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite execução manual do workflow

jobs:
  build:
    name: Jobs to Update Datas
    runs-on: ubuntu-latest
    steps:
      # Gera a animação Snake
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jjfilho # Nome de usuário no GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica o SVG da animação no branch `output`
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
